package pkg21550384_componentesgraficos_u3_md;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Alumnos extends javax.swing.JFrame {

    String sPaísAlumno, sEstadoAlumno;
    String sHardware = "", sSoftware = "", sArquitecturaDeComputadoras = "", sSeguridad = "", sDiseñoWeb = "", sProgramaciónWeb = "", sDesarrolloGráfico = "", sAplicacionesHíbridas = "", sProgramaciónMóvil = "", sRedes = "", sSoporteYMantenimiento = "", sElectrónicaComputacional = "";

    /**
     * Creates new form Alumnos
     */
    public Alumnos() {
        initComponents();

        String[] arrayPaíses = new String[]{"Selecciona País", "México", "Estados Unidos", "Canadá", "Colombia"};
        cbxPaís.setModel(new DefaultComboBoxModel(arrayPaíses));

        // for (int i = 0; i < arrayPaíses.length; i++) {
        //     cbxPaís.addItem(arrayPaíses[i]);
        // }
        lblEstado.setVisible(false);
        cbxEstado.setVisible(false);
        lblCalle.setVisible(false);
        lblNúmero.setVisible(false);
        lblColonia.setVisible(false);
        txtCalle.setVisible(false);
        txtNúmero.setVisible(false);
        txtColonia.setVisible(false);
    }

    // Método para validar si es que se seleccionó o no el checkbox con las preferencias uno a uno.
    private String validarVacío(String sVal) {

        if (sVal.equals("")) {
            return "";
        } else {
            return sVal + "\n";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxPaís = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        rbnDirección = new javax.swing.JRadioButton();
        lblCalle = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        lblNúmero = new javax.swing.JLabel();
        txtNúmero = new javax.swing.JTextField();
        lblColonia = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        chxDiseñoWeb = new javax.swing.JCheckBox();
        chxHardware = new javax.swing.JCheckBox();
        chxArquitecturaDeComputadoras = new javax.swing.JCheckBox();
        chxProgramaciónMóvil = new javax.swing.JCheckBox();
        chxSoftware = new javax.swing.JCheckBox();
        chxProgramaciónWeb = new javax.swing.JCheckBox();
        chxRedes = new javax.swing.JCheckBox();
        chxSeguridad = new javax.swing.JCheckBox();
        chxDesarrolloGráfico = new javax.swing.JCheckBox();
        chxSoporteYMantenimiento = new javax.swing.JCheckBox();
        chxElectrónicaComputacional = new javax.swing.JCheckBox();
        chxAplicacionesHíbridas = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxPaís.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaísActionPerformed(evt);
            }
        });
        getContentPane().add(cbxPaís, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 130, -1));

        jLabel1.setText("Localidad:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, -1));

        lblEstado.setText("Estado:");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        rbnDirección.setText("Con dirección");
        rbnDirección.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnDirecciónActionPerformed(evt);
            }
        });
        getContentPane().add(rbnDirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblCalle.setText("Calle:");
        getContentPane().add(lblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        getContentPane().add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 310, -1));

        lblNúmero.setText("Número:");
        getContentPane().add(lblNúmero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        getContentPane().add(txtNúmero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 310, -1));

        lblColonia.setText("Colonia:");
        getContentPane().add(lblColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        getContentPane().add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 310, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 390, -1));

        chxDiseñoWeb.setText("Diseño web");
        chxDiseñoWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxDiseñoWebActionPerformed(evt);
            }
        });
        getContentPane().add(chxDiseñoWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        chxHardware.setText("Hardware");
        chxHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxHardwareActionPerformed(evt);
            }
        });
        getContentPane().add(chxHardware, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        chxArquitecturaDeComputadoras.setText("Arquitectura de computadoras");
        chxArquitecturaDeComputadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxArquitecturaDeComputadorasActionPerformed(evt);
            }
        });
        getContentPane().add(chxArquitecturaDeComputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        chxProgramaciónMóvil.setText("Programación móvil");
        chxProgramaciónMóvil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxProgramaciónMóvilActionPerformed(evt);
            }
        });
        getContentPane().add(chxProgramaciónMóvil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        chxSoftware.setText("Software");
        chxSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxSoftwareActionPerformed(evt);
            }
        });
        getContentPane().add(chxSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        chxProgramaciónWeb.setText("Programación Web");
        chxProgramaciónWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxProgramaciónWebActionPerformed(evt);
            }
        });
        getContentPane().add(chxProgramaciónWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        chxRedes.setText("Redes");
        chxRedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxRedesActionPerformed(evt);
            }
        });
        getContentPane().add(chxRedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        chxSeguridad.setText("Seguridad");
        chxSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxSeguridadActionPerformed(evt);
            }
        });
        getContentPane().add(chxSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        chxDesarrolloGráfico.setText("Desarrollo gráfico");
        chxDesarrolloGráfico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxDesarrolloGráficoActionPerformed(evt);
            }
        });
        getContentPane().add(chxDesarrolloGráfico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        chxSoporteYMantenimiento.setText("Soporte y mantenimiento");
        chxSoporteYMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxSoporteYMantenimientoActionPerformed(evt);
            }
        });
        getContentPane().add(chxSoporteYMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        chxElectrónicaComputacional.setText("Electrónica Computacional");
        chxElectrónicaComputacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxElectrónicaComputacionalActionPerformed(evt);
            }
        });
        getContentPane().add(chxElectrónicaComputacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        chxAplicacionesHíbridas.setText("Aplicaciones Híbridas");
        chxAplicacionesHíbridas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxAplicacionesHíbridasActionPerformed(evt);
            }
        });
        getContentPane().add(chxAplicacionesHíbridas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 130, 50));

        jLabel7.setText("Preferencias:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel8.setText("País:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbnDirecciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnDirecciónActionPerformed
        // TODO add your handling code here:
        if (rbnDirección.isSelected()) {
            lblCalle.setVisible(true);
            lblNúmero.setVisible(true);
            lblColonia.setVisible(true);
            txtCalle.setVisible(true);
            txtNúmero.setVisible(true);
            txtColonia.setVisible(true);
        } else {
            lblCalle.setVisible(false);
            lblNúmero.setVisible(false);
            lblColonia.setVisible(false);
            txtCalle.setVisible(false);
            txtNúmero.setVisible(false);
            txtColonia.setVisible(false);
        }
    }//GEN-LAST:event_rbnDirecciónActionPerformed

    private void cbxPaísActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaísActionPerformed
        // TODO add your handling code here:

        String sPaís = cbxPaís.getSelectedItem().toString();
        String[] arrayEstados = null;
        switch (sPaís) {
            case "México":
                arrayEstados = new String[]{"Selecciona Estado", "Chihuahua", "Nuevo León", "Guadalajara", "Sonora", "Durango", "Zacatecas"};
                cbxEstado.setModel(new DefaultComboBoxModel(arrayEstados));
                break;
            case "Estados Unidos":
                arrayEstados = new String[]{"Selecciona Estado", "Texas", "Alabama", "Nuevo México", "Washington D.C.", "California", "Nevada"};
                cbxEstado.setModel(new DefaultComboBoxModel(arrayEstados));
                break;
            case "Canadá":
                arrayEstados = new String[]{"Selecciona Estado", "Alberta", "Manitoba", "Nueva escocia", "Nunavut", "Ontario", "Columbia británica"};
                cbxEstado.setModel(new DefaultComboBoxModel(arrayEstados));
                break;
            case "Colombia":
                arrayEstados = new String[]{"Selecciona Estado", "Amazonas", "Antioquía", "Atlántico", "Bolivar", "Meta", "Caldas"};
                cbxEstado.setModel(new DefaultComboBoxModel(arrayEstados));
                break;
            default:
                JOptionPane.showMessageDialog(null, "Selecciona un país para continuar.", "Error de selección", JOptionPane.ERROR_MESSAGE);
                lblEstado.setVisible(false);
                cbxEstado.setVisible(false);
                break;
        }

        if (!sPaís.equals("Selecciona País")) {
            cbxEstado.setModel(new DefaultComboBoxModel(arrayEstados));
            lblEstado.setVisible(true);
            cbxEstado.setVisible(true);
            sPaísAlumno = sPaís;
        }


    }//GEN-LAST:event_cbxPaísActionPerformed

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        // TODO add your handling code here:
        String sEstado = cbxEstado.getSelectedItem().toString();
        if (!sEstado.equals("Selecciona Estado")) {
            sEstadoAlumno = sEstado;
        }
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        // Obteniendo el nombre del formulario
        String sNombreAlumno = txtNombre.getText();
        System.out.println("Nombre: " + sNombreAlumno);

        // Obteniendo el país y el estado del formulario
        System.out.println("Pais: " + sPaísAlumno);
        System.out.println("Estado: " + sEstadoAlumno);

        // Validamos si el radioButton está seleccionado
        if (rbnDirección.isSelected()) {
            // Si está seleccionado obtenemos los valores de la dirección del formulario.
            String sCalleAlumno = txtCalle.getText();
            String sNúmeroAlumno = txtNúmero.getText();
            String sColoniaAlumno = txtColonia.getText();
            System.out.println("Calle: " + sCalleAlumno);
            System.out.println("Número: " + sNúmeroAlumno);
            System.out.println("Colonia: " + sColoniaAlumno);
        }

        System.out.println("Preferencias: \n" + validarVacío(sHardware) + validarVacío(sSoftware) + validarVacío(sSeguridad) + validarVacío(sDiseñoWeb) + validarVacío(sArquitecturaDeComputadoras) + validarVacío(sProgramaciónWeb) + validarVacío(sDesarrolloGráfico) + validarVacío(sAplicacionesHíbridas) + validarVacío(sProgramaciónMóvil) + validarVacío(sRedes) + validarVacío(sSoporteYMantenimiento) + validarVacío(sElectrónicaComputacional));

        /* private String checkboxSeleccionados(JCheckBox chx) {
            String sAcum = "";
        if(chx.getText().equals("Hardware") && chx.isSelected()) {
            sAcum = sAcum + "Hardware, "
        }else if(){
            
        } */

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void chxProgramaciónMóvilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxProgramaciónMóvilActionPerformed
        // TODO add your handling code here:
        if (chxProgramaciónMóvil.isSelected()) {
            sProgramaciónMóvil = "Programación Móvil";
        } else {
            sProgramaciónMóvil = "";
        }
    }//GEN-LAST:event_chxProgramaciónMóvilActionPerformed

    private void chxHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxHardwareActionPerformed
        // TODO add your handling code here:
        if (chxHardware.isSelected()) {
            sHardware = "Hardware";
        } else {
            sHardware = "";
        }
    }//GEN-LAST:event_chxHardwareActionPerformed

    private void chxSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxSoftwareActionPerformed
        // TODO add your handling code here:
        if (chxSoftware.isSelected()) {
            sSoftware = "Software";
        } else {
            sSoftware = "";
        }
    }//GEN-LAST:event_chxSoftwareActionPerformed

    private void chxSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxSeguridadActionPerformed
        // TODO add your handling code here:
        if (chxSeguridad.isSelected()) {
            sSeguridad = "Seguridad";
        } else {
            sSeguridad = "";
        }
    }//GEN-LAST:event_chxSeguridadActionPerformed

    private void chxDiseñoWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxDiseñoWebActionPerformed
        // TODO add your handling code here:
        if (chxDiseñoWeb.isSelected()) {
            sDiseñoWeb = "Diseño Web";
        } else {
            sDiseñoWeb = "";
        }
    }//GEN-LAST:event_chxDiseñoWebActionPerformed

    private void chxArquitecturaDeComputadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxArquitecturaDeComputadorasActionPerformed
        // TODO add your handling code here:
        if (chxArquitecturaDeComputadoras.isSelected()) {
            sArquitecturaDeComputadoras = "Arquitectura de Computadoras";
        } else {
            sArquitecturaDeComputadoras = "";
        }
    }//GEN-LAST:event_chxArquitecturaDeComputadorasActionPerformed

    private void chxProgramaciónWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxProgramaciónWebActionPerformed
        // TODO add your handling code here:
        if (chxProgramaciónWeb.isSelected()) {
            sProgramaciónWeb = "Programación Web";
        } else {
            sProgramaciónWeb = "";
        }
    }//GEN-LAST:event_chxProgramaciónWebActionPerformed

    private void chxDesarrolloGráficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxDesarrolloGráficoActionPerformed
        // TODO add your handling code here:
        if (chxDesarrolloGráfico.isSelected()) {
            sDesarrolloGráfico = "Desarrollo Gráfico";
        } else {
            sDesarrolloGráfico = "";
        }
    }//GEN-LAST:event_chxDesarrolloGráficoActionPerformed

    private void chxAplicacionesHíbridasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxAplicacionesHíbridasActionPerformed
        // TODO add your handling code here:
        if (chxAplicacionesHíbridas.isSelected()) {
            sAplicacionesHíbridas = "Aplicaciones Híbridas";
        } else {
            sAplicacionesHíbridas = "";
        }
    }//GEN-LAST:event_chxAplicacionesHíbridasActionPerformed

    private void chxRedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxRedesActionPerformed
        // TODO add your handling code here:
        if (chxRedes.isSelected()) {
            sRedes = "Redes";
        } else {
            sRedes = "";
        }
    }//GEN-LAST:event_chxRedesActionPerformed

    private void chxSoporteYMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxSoporteYMantenimientoActionPerformed
        // TODO add your handling code here:
        if (chxSoporteYMantenimiento.isSelected()) {
            sSoporteYMantenimiento = "Soporte y Mantenimiento";
        } else {
            sSoporteYMantenimiento = "";
        }
    }//GEN-LAST:event_chxSoporteYMantenimientoActionPerformed

    private void chxElectrónicaComputacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxElectrónicaComputacionalActionPerformed
        // TODO add your handling code here:
        if (chxElectrónicaComputacional.isSelected()) {
            sElectrónicaComputacional = "Electrónica Computacional";
        } else {
            sElectrónicaComputacional = "";
        }
    }//GEN-LAST:event_chxElectrónicaComputacionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxPaís;
    private javax.swing.JCheckBox chxAplicacionesHíbridas;
    private javax.swing.JCheckBox chxArquitecturaDeComputadoras;
    private javax.swing.JCheckBox chxDesarrolloGráfico;
    private javax.swing.JCheckBox chxDiseñoWeb;
    private javax.swing.JCheckBox chxElectrónicaComputacional;
    private javax.swing.JCheckBox chxHardware;
    private javax.swing.JCheckBox chxProgramaciónMóvil;
    private javax.swing.JCheckBox chxProgramaciónWeb;
    private javax.swing.JCheckBox chxRedes;
    private javax.swing.JCheckBox chxSeguridad;
    private javax.swing.JCheckBox chxSoftware;
    private javax.swing.JCheckBox chxSoporteYMantenimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblColonia;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNúmero;
    private javax.swing.JRadioButton rbnDirección;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNúmero;
    // End of variables declaration//GEN-END:variables
}
