/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg21550384_díadelasemana_u2_md;

import javax.swing.JOptionPane;

/**
 *
 * @author chant
 */
public class DíasDeLaSemana extends javax.swing.JFrame {

    /**
     * Creates new form DíasDeLaSemana
     */
    public DíasDeLaSemana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 40, -1));

        btnConvertir.setText("Convertir a texto");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Debes colocar el número del día que quieras conocer:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblResultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg21550384_díadelasemana_u2_md/1aa17813634c4ca0fcc5034399dad5c9.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -5, 410, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // Tipo de dato regular, tipo de dato primitivo [Integer, Double, Float, Boolean, Character, Short, Byte]
        int iNumero = Integer.parseInt(txtNumero.getText());
        /* if(iNumero == 1){
            lblResultado.setText("Lunes");
        }else if(iNumero == 2){
            lblResultado.setText("Martes");
        }else if(iNumero == 3){
            lblResultado.setText("Miércoles");
        }else if(iNumero == 4){
            lblResultado.setText("Jueves");
        }else if(iNumero == 5){
            lblResultado.setText("Viernes");
        }else if(iNumero == 6){
            lblResultado.setText("Sábado");
        }else if(iNumero == 7){
            lblResultado.setText("Domingo");
        }else{
        JOptionPane.showMessageDialog(null, "No existe un día de la semana para ese número", "Error", JOptionPane.ERROR_MESSAGE);
         } */
        
        // El switch es más rápido que el else if
        // Pero solo se puede utilizar con una sola condicional
        // Si tengo 2 o más nos conviene el else if
        switch(iNumero){
            case 1:
                lblResultado.setText("Lunes");
                break;
            case 2:
                lblResultado.setText("Martes");
                break;
            case 3:
                lblResultado.setText("Miércoles");
                break;
            case 4:
                lblResultado.setText("Jueves");
                break;
            case 5:
                lblResultado.setText("Viernes");
                break;
            case 6:
                lblResultado.setText("Sábado");
                break;
            case 7:
                lblResultado.setText("Domingo");
                break;
            default:
                JOptionPane.showMessageDialog(null, "No existe un día de la semana para ese número", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DíasDeLaSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DíasDeLaSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DíasDeLaSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DíasDeLaSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DíasDeLaSemana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
