/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg21550384_exa1_u1_md;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author chant
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtC1 = new javax.swing.JTextField();
        txtP1 = new javax.swing.JTextField();
        txtC2 = new javax.swing.JTextField();
        txtP2 = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\chant\\Downloads\\10832.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtC1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, 20));

        txtP1.setEditable(false);
        txtP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, 40));
        getContentPane().add(txtC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 140, 20));

        txtP2.setEditable(false);
        txtP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 140, 40));

        txtC.setEditable(false);
        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });
        getContentPane().add(txtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 160, 70));

        btn1.setText("Mostrar");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        btn2.setText("Mostrar");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        btnS.setText("   X");
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });
        getContentPane().add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel2.setText("¡Bienvenido a ColorLand!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 200, -1));

        jLabel3.setText("Tu color combinado es");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Puedes elegir entre los siguientes colores: azul, verde, rojo, amarillo, cian o magenta.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP1ActionPerformed

    private void txtP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String sColor1 = txtC1.getText();
        if(sColor1.equalsIgnoreCase("rojo")) {
           txtP1.setBackground(Color.red);
        }
        else if(sColor1.equalsIgnoreCase("azul")) {
           txtP1.setBackground(Color.blue);
        }
        else if(sColor1.equalsIgnoreCase("amarillo")) {
           txtP1.setBackground(Color.yellow);
        }
        else if(sColor1.equalsIgnoreCase("verde")) {
           txtP1.setBackground(Color.green);
        }
        else if(sColor1.equalsIgnoreCase("cian")) {
           txtP1.setBackground(Color.cyan);
        }
        else if(sColor1.equalsIgnoreCase("magenta")) {
           txtP1.setBackground(Color.magenta);
        }
        else{
            JOptionPane.showMessageDialog(null, "No puede usar ese color ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSActionPerformed

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        // TODO add your handling code here:
        //if(sColorC1 == "rojo" &&  sColorC2=="azul"){
            
        }
    }//GEN-LAST:event_txtCActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        String sColor2 = txtC2.getText();
        if(sColor2.equalsIgnoreCase("rojo")) {
           txtP2.setBackground(Color.red);
        }
        else if(sColor2.equalsIgnoreCase("azul")) {
           txtP2.setBackground(Color.blue);
        }
        else if(sColor2.equalsIgnoreCase("amarillo")) {
           txtP2.setBackground(Color.yellow);
        }
        else if(sColor2.equalsIgnoreCase("verde")) {
           txtP2.setBackground(Color.green);
        }
        else if(sColor2.equalsIgnoreCase("cian")) {
           txtP2.setBackground(Color.cyan);
        }
        else if(sColor2.equalsIgnoreCase("magenta")) {
           txtP2.setBackground(Color.magenta);
        }
        else{
            JOptionPane.showMessageDialog(null, "No puede usar ese color ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btnS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtC1;
    private javax.swing.JTextField txtC2;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP2;
    // End of variables declaration//GEN-END:variables
}
