
package pkg21550384_númerosaleatorios_u2_md;

public class Números extends javax.swing.JFrame {

    /**
     * Creates new form Números
     */
    public Números() {
        initComponents();
    }

    private int encontrarRepetido(int[] arreglo, int iRandom, int iCantEquipos){
        for (int j = 0; j < arreglo.length; j++) {
             if(arreglo[j] == iRandom){
                 iRandom = numeroAleatorio(iCantEquipos);
                 j = -1;
             }
                }
        return iRandom;
    }
    
    private int numeroAleatorio(int iCantEquipos){
        int iVariable = (int) (Math.random()* iCantEquipos + 1);
        return iVariable;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEquipos = new javax.swing.JTextField();
        btnMezclar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 70, -1));

        btnMezclar.setText("Mezclar");
        btnMezclar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezclarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMezclar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        lblResultado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 190, 30));

        jLabel1.setText("Cantidad de equipos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 10, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMezclarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclarActionPerformed
        String sVal = txtEquipos.getText();
        int iCantEquipos = Integer.parseInt(sVal);
        int[] iArray = new int[iCantEquipos];
        for (int i = 0; i < iCantEquipos; i++) {
            int iRandom = numeroAleatorio(iCantEquipos);
            
            if(i == 0){
                iArray[i] = iRandom;
                lblResultado.setText(String.valueOf(iArray[i]));
            }else{
              iArray[i] = encontrarRepetido(iArray, iRandom, iCantEquipos);  
              lblResultado.setText(lblResultado.getText() + ", " + String.valueOf(iArray[i]));
            }
            
        }
        // Shit + Alt + F (Acomodar)
        // Ctrl + F (Búsqueda de algo que pusimos)
        // Ctrl + R = Refactor (renombrar)
    }//GEN-LAST:event_btnMezclarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Números.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Números.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Números.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Números.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Números().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMezclar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtEquipos;
    // End of variables declaration//GEN-END:variables
}
