/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg21550384_numerosdivisibles_u2_md;

import javax.swing.JFormattedTextField;

/**
 *
 * @author chant
 */
public class NúmerosDivisibles extends javax.swing.JFrame {

    /**
     * Creates new form NúmerosDivisibles
     */
    public NúmerosDivisibles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblD2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNúmero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblD3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese un número");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        lblD2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 260, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Números divisibles");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        txtNúmero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNúmeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNúmero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Divisibles entre 2:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Divisibles entre 3:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lblD3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 185, 260, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\chant\\Downloads\\N.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNúmeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNúmeroActionPerformed
        String sConcatena1 = "";
        String sConcatena2 = "";
        String sNúmero = txtNúmero.getText();
        int iNúmero = Integer.parseInt(sNúmero);
       for (int i = 0; i <= iNúmero; i++){
           if(i % 2 == 0){
               sConcatena1 += i + ", ";     
           lblD2.setText(sConcatena1);
            }
       }
       for (int i = 0; i <= iNúmero; i++){
           if(i % 3 == 0){
               sConcatena2 += i + ", "; 
            lblD3.setText(sConcatena2);
            }         
        }
    }//GEN-LAST:event_txtNúmeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NúmerosDivisibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NúmerosDivisibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NúmerosDivisibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NúmerosDivisibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NúmerosDivisibles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblD3;
    private javax.swing.JTextField txtNúmero;
    // End of variables declaration//GEN-END:variables
}
