package p1_equipos_camelcase_md;

import javax.swing.JOptionPane;

public class principal extends javax.swing.JFrame {
    public principal() {
        initComponents();
    }
    public int contarPalabras(String s_cc){
        int i_c = 0;
        char [] arreglo_camello = s_cc.toCharArray(); // Arreglo de carácteres
        /* Existen dos tipos de notación para identificadores:
            Upper Camel Case: toda letra inicial de palabra en mayúsculas (Upper) y el resto de palabra en minúsculas y las siguientes palabras, la letra inicial en mayúsculas (Upper) y el resto de palabra en minúscula. Usaremos Upper Camel Case para las clases, por ejemplo HolaMundo.
            Lower Camel Case:  toda la palabra inicial en minúsculas (Lower) y la siguiente palabra comenzará con la primera letra inicial en mayúsculas y el resto de la palabra en minúsculas. Usaremos Lower Camel Case para los métodos y variables como por ejemplo: int valorEntero = 0 */
        for (int i = 0; i < arreglo_camello.length - 1; i++) {
            arreglo_camello[0] = Character.toUpperCase(arreglo_camello[0]); // Convertimos en mayúscula la primera letra de la cadena para que se contabilice
            if(arreglo_camello[i] >= 65 && arreglo_camello[i] <= 90){ // Cuenta si en el arreglo hay un carácter en letra mayúscula según el Código ASCII.
                i_c++;
            }
        }
        return i_c;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_camel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_palabras = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_camel.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txt_camel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_camelKeyTyped(evt);
            }
        });
        getContentPane().add(txt_camel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 270, 30));

        jButton1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Contar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 70, 20));

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Ingresa una frase en escritura camello: ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        lbl_palabras.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        lbl_palabras.setForeground(new java.awt.Color(0, 0, 0));
        lbl_palabras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_palabras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_palabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 70, 20));

        jButton2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 0));
        jButton2.setText("Borrar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 60, 30));

        jButton3.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("Salir");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 60, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Su frase contiene las siguientes palabras en escritura camello:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p1_equipos_camelcase_md/Camello.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lbl_palabras.setText(String.valueOf(contarPalabras(txt_camel.getText()))); // Muestra el número de palabras
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txt_camel.setText("");
        lbl_palabras.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_camelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_camelKeyTyped
        /* Esto era por si sólo queríamos Lower Camel Case, en dado caso de que únicamente eso necesitemos.
         String s_cc = txt_camel.getText(); 
        char [] arreglo_camello = s_cc.toCharArray(); // Arreglo de carácteres
        for(int i=0;i<arreglo_camello.length;i++){
        
            if(arreglo_camello[0] >= 65 && arreglo_camello[0] <= 90){ // Código ASCII Mayúsculas
            Character.isUpperCase(evt.getKeyChar());
            evt.consume();
            txt_camel.setText("");
            JOptionPane.showMessageDialog(null, "La escritura camello no inicia con mayúscula, vuelva a intentar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } */
                
    }//GEN-LAST:event_txt_camelKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_palabras;
    private javax.swing.JTextField txt_camel;
    // End of variables declaration//GEN-END:variables
}