/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg21550384_binarioadecimal_u1_md;

import javax.swing.JOptionPane;

/**
 *
 * @author chant
 */
public class ConvertidorBinarioDecimal extends javax.swing.JFrame {

    /**
     * Creates new form ConvertidorBinarioDecimal
     */
    public ConvertidorBinarioDecimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBinario = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDecimal = new javax.swing.JTextField();
        btnConvertidorDecimal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtBinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 240, -1));

        btnConvertir.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel2.setText("Escribe un número binario para convertirlo en decimal:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 320, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        txtDecimal.setEditable(false);
        txtDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDecimalActionPerformed(evt);
            }
        });
        getContentPane().add(txtDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, -1));

        btnConvertidorDecimal.setText("Convertidor decimal a binario");
        btnConvertidorDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertidorDecimalActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvertidorDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\chant\\Downloads\\W.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        String sBinario = txtBinario.getText();
        // arreglo de caracteres - conjunto de caracteres que forman una unión // L u i s
        // Los corchotes generan una arreglo, un grupo de tipos de dato []
        char[] arregloBinario = sBinario.toCharArray();
        // Ciclos - Oraciones repetitivas que se ejecutan para formar un solo fin, Tipos: For, while, dowhile
       // De donde empieza , hasta donde recorrer, de cuánto en cuánto va subiendo
       // numero = Integer.parseInt(AquíTieneQueHaberUnaString
       // String = String.valueOf(Char o int o double o boolean o float)
       // Casteo = Forzar a la operación a que sea de un tipo de valor o tipo de dato específico (int)
       // += iSumatoria = iSumatoria +
       int iSumatoria = 0;
       int tamanio = arregloBinario.length - 1;
       for(int i=0; i < arregloBinario.length; i++){
           iSumatoria += (int) (Integer.parseInt(String.valueOf(arregloBinario[i])) * Math.pow(2, tamanio));
           tamanio = tamanio - 1;
             }            
                txtDecimal.setText(String.valueOf(iSumatoria));
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void txtDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDecimalActionPerformed

    }//GEN-LAST:event_txtDecimalActionPerformed

    private void btnConvertidorDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertidorDecimalActionPerformed
        // TODO add your handling code here:
        ConvertidorDecimalBinario cObjt = new ConvertidorDecimalBinario();
        cObjt.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConvertidorDecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertidorBinarioDecimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertidorBinarioDecimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertidorBinarioDecimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertidorBinarioDecimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertidorBinarioDecimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertidorDecimal;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtBinario;
    private javax.swing.JTextField txtDecimal;
    // End of variables declaration//GEN-END:variables
}
